Pass OCI Catalog URL through to syncer. (#6720)
### Description of the change

Updates the dev chart and snippets of code so that if the OCI-Catalog
service is enabled, the URL is passed all the way through to the sync
job.

Verified from the logs:

```
I0829 01:33:33.729325       1 root.go:32] "The component 'asset-syncer' has been configured with" serverOptions={"DatabaseURL":"kubeapps-postgresql:5432","DatabaseName":"assets","DatabaseUser":"postgres","DatabasePassword":"REDACTED","Debug":false,"Namespace":"default","OciRepositories":[],"TlsInsecureSkipVerify":false,"FilterRules":"","PassCredentials":false,"UserAgent":"asset-syncer/903124d9eb9976d7cad846331c20440132b143df (kubeapps/DEVEL)","UserAgentComment":"kubeapps/DEVEL","GlobalPackagingNamespace":"kubeapps","KubeappsNamespace":"","AuthorizationHeader":"","DockerConfigJson":"","OCICatalogURL":"kubeapps-internal-kubeappsapis:50061"}
I0829 01:33:34.926684       1 utils.go:495] Unable to find VAC index: .... Attempting OCI-Catalog
Error: error: GET request to [https://registry-1.docker.io/v2/bitnamicharts/airflow/tags/list] failed due to status [401]: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"bitnamicharts/airflow","Action":"pull"}]}]}

```

### Benefits

Can start next step of getting an anon token to continue the sync.

### Possible drawbacks


### Applicable issues


- ref #6706 

### Additional information

This should really have been done as part of the previous #6263 where I
updated the sync code to use the new service, but didn't hook it up.

---------

Signed-off-by: Michael Nelson <minelson@vmware.com>