Fix local_e2e_tests CI job (#7889)
Fix local_e2e_tests CI job
<!--
Before you open the request please review the following guidelines and
tips to help it be more easily integrated:

 - Describe the scope of your change - i.e. what the change does.
 - Describe any known limitations with your change.
- Please run any tests or examples that can exercise your modified code.

 Thank you for contributing!
 -->

### Description of the change

CI is broken at `local_e2e_tests` in the kubeapps-general workflow for
the following reasons:
* It's failing at the `Export cluster variables` step because it's
unable to get the DEX IP. The error happens because `docker network
inspect kind| jq '.[0].IPAM.Config` returns where the item we are
looking for has been moved from the first to the second position ([0] ->
[1]).
* It's failing for the flux test group because it's unable to install
Flux due to a 404 response from the server.

### Benefits

The CI works again.
<!-- What benefits will be realized by the code change? -->

### Possible drawbacks

This is not the ideal solution because is fragile. If the order of the
items in the array change again the future, the CI will be broken again.
<!-- Describe any known limitations with your change -->

### Applicable issues

<!-- Enter any applicable Issues here (You can reference an issue using
#) -->

- fixes #

### Additional information

Sample failing job:
https://github.com/vmware-tanzu/kubeapps/actions/runs/9850222972/job/27223662707

```
DEFAULT_DEX_IP=172.18.0.2
DEX_IP=null...1
ADDITIONAL_CLUSTER_IP=null...2
Context "kind-kubeapps-ci" modified.
Default IP does not match with current IP used in Kind
Error: Process completed with exit code 1.
```

This is the output of `docker network inspect kind| jq '.[0].IPAM'`:

```bash
runner@fv-az573-34:~/work/kubeapps/kubeapps$ docker network inspect kind| jq '.[0].IPAM'
{
  "Driver": "default",
  "Options": {},
  "Config": [
    {
      "Subnet": "fc00:f853:ccd:e793::/64"
    },
    {
      "Subnet": "172.18.0.0/16",
      "Gateway": "172.18.0.1"
    }
  ]
}
<!-- If there's anything else that's important and relevant to your pull
request, mention that information here.-->

---------

Signed-off-by: Jesús Benito Calzada <jesus.benito@broadcom.com>